create table entry (
  id bigint generated by default as identity,
  credit decimal(19,2),
  date timestamp,
  debit decimal(19,2),
  description varchar(255),
  reference varchar(255),
  version integer, primary key (id));

create table rule (
id bigint generated by default as identity,
tag varchar(255),
exclude bit,
is_savings bit,
version integer, primary key (id));

create table rule_patterns (
rule_id bigint not null,
patterns varchar(255));

alter table rule_patterns add constraint FK_48ji33soehgic1pq2rqhkkxpw foreign key (rule_id) references rule;